export const APP_WRITE_ID = '65fb4d6297b97b3d1a25'
export const DB_ID = 'crm-base'
export const COLLECTION_DEALS = 'deals'
export const COLLECTION_CUSTOMERS = 'customers'
export const COLLECTION_COMMENTS = 'comments'
export const STORAGE_ID = 'storage'
